name: hufniture
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  flutter_onboarding_slider: ^1.0.11
  ionicons: ^0.2.2
  salomon_bottom_bar: ^3.3.2
  carousel_slider: ^4.2.1
  flutter_staggered_grid_view: ^0.7.0
  contained_tab_bar_view: ^0.8.0
  currency_formatter: ^2.0.0
  cached_network_image: ^3.3.1
  loading_animation_widget: ^1.2.1
  motion_toast: ^2.10.0
  flutter_slidable: ^3.1.0
  order_tracker_zen: ^1.0.0+4
  intl: ^0.18.1
  http: ^1.2.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Regular.ttf
        - asset: assets/fonts/LeagueSpartan-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-light.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
